version: "3.8"

services:
    mysqldb:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_TCP_PORT=$MYSQL_DOCKER_PORT
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        expose:
            - $MYSQL_DOCKER_PORT
